// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Conssecionaria.DATA.Models;

public partial class Checagem
{
    [Key]
    public int ChecagemId { get; set; }

    public int ClienteId { get; set; }

    public int MotoId { get; set; }

    public int Nota { get; set; }

    [Required]
    [StringLength(10)]
    public string Vendedor { get; set; }

    [StringLength(50)]
    public string Obs { get; set; }

    [ForeignKey("ClienteId")]
    [InverseProperty("Checagem")]
    public virtual Cliente Cliente { get; set; }

    [ForeignKey("MotoId")]
    [InverseProperty("Checagem")]
    public virtual Moto Moto { get; set; }
}