// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Conssecionaria.DATA.Models;

public partial class Cliente
{
    [Key]
    public int ClienteId { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Nome { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string Fone { get; set; }

    [Required]
    [Column("CPF")]
    [StringLength(14)]
    [Unicode(false)]
    public string Cpf { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string CliEndereco { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string CliCidade { get; set; }

    [StringLength(75)]
    [Unicode(false)]
    public string CliBairro { get; set; }

    [StringLength(25)]
    [Unicode(false)]
    public string CliNumero { get; set; }

    [InverseProperty("Cliente")]
    public virtual ICollection<Checagem> Checagem { get; set; } = new List<Checagem>();
}