// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Conssecionaria.DATA.Models;

public partial class ConcessionariaContext : DbContext
{
    public ConcessionariaContext()
    {
    }

    public ConcessionariaContext(DbContextOptions<ConcessionariaContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Checagem> Checagem { get; set; }

    public virtual DbSet<Cliente> Cliente { get; set; }

    public virtual DbSet<Moto> Moto { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Data Source=DESKTOP-E1QRAOC;Initial Catalog=Concessionaria;Integrated Security=True;Encrypt=False");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Checagem>(entity =>
        {
            entity.Property(e => e.Obs).IsFixedLength();
            entity.Property(e => e.Vendedor).IsFixedLength();

            entity.HasOne(d => d.Cliente).WithMany(p => p.Checagem)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Checagem_Cliente");

            entity.HasOne(d => d.Moto).WithMany(p => p.Checagem)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Checagem_Moto");
        });

        modelBuilder.Entity<Moto>(entity =>
        {
            entity.Property(e => e.Ano).IsFixedLength();
            entity.Property(e => e.Modelo).IsFixedLength();
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}