// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Conssecionaria.DATA.Models;

public partial class Moto
{
    [Key]
    public int MotoId { get; set; }

    [Required]
    [StringLength(5)]
    public string Ano { get; set; }

    [Required]
    [StringLength(10)]
    public string Modelo { get; set; }

    public long? Valor { get; set; }

    [InverseProperty("Moto")]
    public virtual ICollection<Checagem> Checagem { get; set; } = new List<Checagem>();
}